import sys
import os
from pathlib import Path
from io import BytesIO
import base64

api = None

# 在导入 PIL 前，确保 DLL 搜索路径正确
_plugin_dir = Path(__file__).parent
if str(_plugin_dir) not in sys.path:
    sys.path.insert(0, str(_plugin_dir))

# 设置 DLL 搜索路径（Windows 特定）
try:
    os.add_dll_directory(str(_plugin_dir))
except Exception:
    pass


def apprun(ctx: dict) -> dict:
    """
    插件初始化入口
    """
    global api
    try:
        from xlz_sdk import Bridge
        api = Bridge(ctx["dll_path"])
        api.output_log("[Pillow演示] 初始化成功，支持 pillow 图片生成")
    except Exception as e:
        api = None
        api.output_log(f"[Pillow演示] 初始化失败: {e}")

    return {
        "app_name": "Pillow 外部依赖演示",
        "author": "Python SDK",
        "app_version": "1.0.0",
        "description": "演示如何在 Python 插件中使用外部依赖（Pillow）生成图片",
        "permissions": ["输出日志", "发送群消息", "上传群图片"],
    }


def _generate_test_image() -> bytes:
    """
    使用 Pillow 生成测试图片
    返回图片的二进制数据
    """
    try:
        from PIL import Image, ImageDraw
    except ImportError as e:
        if api:
            api.output_log(f"[Pillow演示] 导入失败: {e}")
        return None

    try:
        # 创建图片 (400x300, 白色背景)
        img = Image.new("RGB", (400, 300), color="white")
        draw = ImageDraw.Draw(img)

        # 绘制标题
        draw.text((20, 20), "Pillow Test Image", fill="black")
        draw.text((20, 50), "XiaoLiZi VM Python SDK", fill="blue")

        # 绘制一些几何图形
        draw.rectangle([50, 100, 150, 150], outline="red", width=2)
        draw.ellipse([200, 100, 300, 150], outline="green", width=2)
        draw.polygon([(50, 200), (100, 250), (150, 200)], outline="purple", width=2)

        # 绘制文字
        draw.text((50, 260), "Generated by Pillow", fill="gray")

        # 保存到内存
        buf = BytesIO()
        img.save(buf, format="PNG")
        return buf.getvalue()
    except Exception as e:
        if api:
            api.output_log(f"[Pillow演示] 生成图片异常: {e}")
        return None


def on_enable() -> int:
    """
    插件被启用时调用（无参数）
    返回值: 0=正常，1=拒绝启用（框架将停止加载该插件）
    """
    if api is None:
        return 0
    api.output_log("[Pillow演示] 插件已启用")
    return 0


def on_group_message(ev: dict) -> int:
    """
    收到群消息时调用
    返回值: 0=继续传递，1=拦截
    """
    if api is None:
        return 0

    content = (ev.get("message") or "").strip()

    if content == "pillow测试":
        api.output_log("[Pillow演示] 收到 pillow 测试命令，正在生成图片...")

        # 生成图片
        img_data = _generate_test_image()
        if img_data is None:
            api.output_log("[Pillow演示] 生成图片失败")
            return 0

        # 将图片转为 base64（用于演示）
        img_b64 = base64.b64encode(img_data).decode("utf-8")
        api.output_log(f"[Pillow演示] 图片已生成，大小: {len(img_data)} 字节")

        # 上传群图片并获取图片代码
        import ctypes
        api.output_log(f"[Pillow演示] 图片已生成，大小: {len(img_data)} 字节，开始上传...")
        img_code = api.upload_group_image(
            ev.get("this_qq", 0),
            ev.get("group_qq", 0),
            False,
            img_data,
        )
        api.output_log(f"[Pillow演示] upload_group_image 返回: {repr(img_code)}")

        # 发送消息（包含图片代码）
        msg = f"[Pillow演示] 已生成测试图片\n图片大小: {len(img_data)} 字节\nBase64 长度: {len(img_b64)}{img_code}"
        api.send_group_message(
            ev.get("this_qq", 0),
            ev.get("group_qq", 0),
            msg,
            False,
        )

    return 0


def on_private_message(ev: dict) -> int:
    """
    收到私聊消息时调用
    """
    return 0


def on_event_message(ev: dict) -> int:
    """
    收到事件消息时调用
    """
    return 0


def on_setting():
    """
    用户点击"插件设置"时调用（无参数）
    """
    pass


def on_disable():
    """
    插件被禁用时调用（无参数）
    """
    return 0


def on_uninstall():
    """
    插件被卸载时调用（无参数）
    """
    return 0
